easy_sites:
  - name: Machine Learning Jobs UK
    url: https://machinelearningjobs.co.uk/
  - name: Jobs.ac.uk ML
    url: https://www.jobs.ac.uk/search/?placeId=ChIJqZHHQhE7WgIReiWIMkOg-MQ&country%5B%5D=United+Kingdom&country%5B%5D=GB&keywords=machine+learning&location=United+Kingdom
    # url: https://www.jobs.ac.uk/categories/machine-learning-engineer-jobs/2
  - name: King's College London
    url: https://www.kcl.ac.uk/jobs/research-jobs

medium_sites:
  - name: Imperial College
    url: https://www.imperial.ac.uk/jobs/search-internal/
  - name: UCL
    url: https://www.ucl.ac.uk/work-at-ucl/search-ucl-jobs
  - name: Glassdoor
    url: https://www.glassdoor.co.uk/Job/uk-machine-learning-jobs-SRCH_IL.0,2_IN2_KO3,20.htm
  - name: Queen Mary
    url: https://www.qmul.ac.uk/jobs/vacancies/
    
hard_sites:
  - name: LinkedIn
    url: https://www.linkedin.com/jobs/search/?keywords=ai%20research%20uk
  - name: Indeed
    url: https://www.indeed.co.uk/jobs?q=machine+learning&l=United+Kingdom
